baseURL = "https://www.outerrim.cc/"
languageCode = "en-us"

theme = "hyde-hyde"

[params]
    description = "Stuff to read while heading to Tosche Station to pick up some power converters..."
    mainSection = ["posts"]

    logoimage = "/img/logo.svg"
    copyright = "vgroove"
    since = 2021
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

    highlightjs = true
    highlightjsstyle = "github"

    relatedPosts = true

    disqusShortname = "disqus-shortname"
    UtterancesRepo = "vgroove/outerrim"
    UtterancesIssueTerm = "pathname"
    UtterancesTheme = "github-light"

[params.social]
    github = "vgroove"
    rss = "https://www.outerrim.cc/posts/index.xml"
    email = "outerrimblog@gmail.com"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    weight = 200
    identifier = "about"
    url = "/about/"
